inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - '**/bin/**/*'
    - '**/tmp/**/*'
    - '**/script/**/*'
    - '**/template/**/*'
    - '*.gemspec'
  UseCache: true
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false
