---
  address: localhost
  port: 4567
  environment: development
  chdir: /Users/le_fnord/sandbox/work/xmi-related/xmi-viewer
  pid: /Users/le_fnord/sandbox/work/xmi-related/xmi-viewer/tmp/thin.pid
  rackup: /Users/le_fnord/sandbox/work/xmi-related/xmi-viewer/config.ru
  log: /Users/le_fnord/sandbox/work/xmi-related/xmi-viewer/log/thin.log
  max_conns: 1024
  max_persistent_conns: 16
  timeout: 600
  daemonize: false
