---
  environment: production
  chdir: path
  address: 127.0.0.1
  port: 9292
  pid: path/tmp/thin.pid
  rackup: path/config.ru
  log: path/log/thin.log
  max_conns: 1024
  timeout: 180
  max_persistent_conns: 512
  daemonize: true
